/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCombination: typeof import('./src/components/Script/ActionCombination.vue')['default']
    AddModuleDrawer: typeof import('./src/components/Requirement/AddModuleDrawer.vue')['default']
    AddProject: typeof import('./src/components/Project/AddProject.vue')['default']
    AddRequirementDocx: typeof import('./src/components/Requirement/AddRequirementDocx.vue')['default']
    CreateProject: typeof import('./src/components/ProjectManage/CreateProject.vue')['default']
    CustomerManage: typeof import('./src/components/CustomerManage/CustomerManage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Empty: typeof import('./src/components/Empty.vue')['default']
    FunctionModule: typeof import('./src/components/Requirement/FunctionModule.vue')['default']
    FunctionPoint: typeof import('./src/components/Requirement/FunctionPoint.vue')['default']
    GroupManage: typeof import('./src/components/GroupManage/GroupManage.vue')['default']
    HistoryVersionModal: typeof import('./src/components/Requirement/HistoryVersionModal.vue')['default']
    Home: typeof import('./src/components/Home/Home.vue')['default']
    LabelManage: typeof import('./src/components/LabelManage/LabelManage.vue')['default']
    LabelSelect: typeof import('./src/components/LabelManage/LabelSelect.vue')['default']
    LabelSelector: typeof import('./src/components/LabelManage/LabelSelector.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu/LeftMenu.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MetaAction: typeof import('./src/components/Script/MetaAction.vue')['default']
    ProjectDetail: typeof import('./src/components/Project/ProjectDetail.vue')['default']
    ProjectManage: typeof import('./src/components/ProjectManage/ProjectManage.vue')['default']
    Registry: typeof import('./src/components/Registry.vue')['default']
    RequirementDocx: typeof import('./src/components/Requirement/RequirementDocx.vue')['default']
    RequirementManage: typeof import('./src/components/Requirement/RequirementManage.vue')['default']
    RoleManage: typeof import('./src/components/RoleManage/RoleManage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptFile: typeof import('./src/components/Script/ScriptFile.vue')['default']
    TopBar: typeof import('./src/components/TopBar/TopBar.vue')['default']
    UseCase: typeof import('./src/components/UseCase/UseCase.vue')['default']
    UserManage: typeof import('./src/components/UserManage/UserManage.vue')['default']
  }
}
